### ISSUE TITLE
TypeError: helpers.findFile is not a function

### ISSUE THREAD

**Issue by LoranceChen** [AtomLinter/linter-scalac#28]
It occurred when I save file (cmd + s).The top two of stack show as this:
 at Object.provider.lint (/Users/lorancechen/.atom/packages/linter-scalac/lib/linter-scalac.coffee:37:20)
 at promises.push.Promise.then._this.emitter.emit.linter (/Users/lorancechen/.atom/packages/linter/lib/linter-registry.js:63:26)

**Comment by Arcanemagus** [comment]
If I had to guess this is the same old bug of Atom not respecting package npm dependencies when multiple Atom packages depend on the same library (https://github.com/atom/atom/issues/9775) since that could only be triggered if this was using the v4.x.x version of `atom-linter` instead of its requested version of v2.x.x.

Luckily the fix is to just publish the current version, which has now been done as v1.2.0 :wink:. Let us know if you are seeing any further issues after updating.
